Skarea/SP_app/urls.py
from django.urls import path

from SP_app.views import AccountDeleteView, AccountDetailView, AccountUpdateView, hello_world, AccountCreateView
from django.contrib.auth.views import LoginView, LogoutView

app_name ="SP_app"

urlpatterns = [
    path('hello_world/', hello_world, name="hello_world"),
    
    path('login/', LoginView.as_view(template_name="SP_app/login.html"), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    
    path("create/", AccountCreateView.as_view(), name="create"),
    path("detail/<int:pk>", AccountDetailView.as_view(), name="detail"),
    path("update/<int:pk>", AccountUpdateView.as_view(), name="update"),
    path("delete/<int:pk>", AccountDeleteView.as_view(), name="delete"),
]

Skarea/Skarea/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('SP_app/', include('SP_app.urls')),
    path("profiles/", include("profileapp.urls")),
    path("articleapp/" , include("articleapp.urls")),
    path("comment/", include('commentapp.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Skarea/articleapp/urls.py
from re import template
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDeleteView, ArticleDetailView, ArticleListView, ArticleUpdateView
app_name = "articleapp"
urlpatterns = [
    path("list/", ArticleListView.as_view(), name="list"),
    path("create/", ArticleCreateView.as_view(), name="create" ),
    path("detail/<int:pk>", ArticleDetailView.as_view(), name="detail" ),
    path("update/<int:pk>", ArticleUpdateView.as_view(), name="update" ),
    path("delete/<int:pk>", ArticleDeleteView.as_view(), name="delete" ),
]

Skarea/templates/base.html
<!DOCTYPE html>
<html lang="ko">
{% include  "head.html" %}
<body>
    
{% include "header.html"%}

<hr>

{% block content %}
{% endblock %}

<hr>

{% include "footer.html"%}
</body>
</html>

Skarea/templates/footer.html
<div class="footer">
    
        <div style ="font-size: 0.8em;" class=menu>
            <span>공지사항</span> |
            <span>제휴문의</span> |
            <span>서비스 소개</span>
        </div>
    
        <div style="margin-top: 1rem; ">
            <h5 class="Skarea_footer">Skarea</h6>
        </div>
</div>

Skarea/templates/head.html
{% load static %}
<head>
    <meta charset="UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Skarea</title>
    <!-- BOOTSTRAP LINK -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    <!-- GOOGLE FONTS LINK-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Song+Myung&display=swap" rel="stylesheet"> 
   
    <!-- DEFAULT CSS LINK-->
    <link rel="stylesheet" type="text/css" href="{% static "base.css" %}">

    <style>
     
    </style>
</head>

Skarea/templates/header.html
<class= "header" >
<div style="text-align:center; margin: 2rem 0; font-family: 'Song Myung', serif;">
    <div>
        <h1>Skarea</h1>
    </div>

    <div>
        <a href="{% url 'articleapp:list' %}">
            <span>Articles</span>
        </a>
        <span>nav2</span>
        <span>nav3</span>
        {% if not user.is_authenticated %}
        <a href="{% url 'SP_app:login' %}?next={{ request.path }}">
            <span>Login</span>
        </a>
        <a href="{% url 'SP_app:create' %}?next={{ request.path }}">
            <span>SignUp</span>
        </a>
        {% else %}
        <a href="{% url 'SP_app:detail' pk=user.pk %}">
            <span>MyPage</span>
        </a>

        <a href="{% url 'SP_app:logout' %}?next={{ request.path }}">
            <span>Logout</span>
        </a>
        {% endif %}

    </div>
</div>
</class>