Skarea/SP_app/urls.py
from django.urls import path

from SP_app.views import AccountDeleteView, AccountDetailView, AccountUpdateView, hello_world, AccountCreateView
from django.contrib.auth.views import LoginView, LogoutView

app_name ="SP_app"

urlpatterns = [
    path('hello_world/', hello_world, name="hello_world"),
    
    path('login/', LoginView.as_view(template_name="SP_app/login.html"), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    
    path("create/", AccountCreateView.as_view(), name="create"),
    path("detail/<int:pk>", AccountDetailView.as_view(), name="detail"),
    path("update/<int:pk>", AccountUpdateView.as_view(), name="update"),
    path("delete/<int:pk>", AccountDeleteView.as_view(), name="delete"),
]

Skarea/Skarea/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('SP_app/', include('SP_app.urls')),
    path("profiles/", include("profileapp.urls")),
    path("articleapp/" , include("articleapp.urls")),
    path("comment/", include('commentapp.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Skarea/profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView


app_name= "profileapp"


urlpatterns=[
    path("create/", ProfileCreateView.as_view(), name="create"),
    path("update/<int:pk>", ProfileUpdateView.as_view(), name="update"),
]

Skarea/SP_app/models.py
from django.db import models

# Create your models here.
class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

Skarea/SP_app/forms.py
from django.contrib.auth.forms import UserCreationForm  

class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.fields["username"].disabled = True

Skarea/SP_app/views.py
import logging
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy
from SP_app.decorators import account_ownership_required
from SP_app.forms import AccountUpdateForm
from SP_app.models import HelloWorld
from django.views.generic import CreateView , DetailView , UpdateView , DeleteView
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
# Create your views here.
has_ownership = [account_ownership_required , login_required]
def hello_world(request):
    if request.user.is_authenticated:
        
        if request.method == "POST":
        
            temp= request.POST.get("hello_world_input")
        
            new_hello_world = HelloWorld()
            new_hello_world.text = temp
            new_hello_world.save()
        
            return HttpResponseRedirect(reverse('SP_app:hello_world'))
        else:
            hello_world_list = HelloWorld.objects.all()
            return render(request, "SP_app/hello_world.html", context={"hello_world_list": hello_world_list})
    
    else:
        return HttpResponseRedirect(reverse("SP_app:login"))
class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy("SP_app:hello_world")
    template_name = "SP_app/create.html"    
    
class AccountDetailView(DetailView):
    model= User
    context_object_name= "target_user"
    template_name = "SP_app/detail.html"
    
@method_decorator(has_ownership, "get")
@method_decorator(has_ownership, "post")
class AccountUpdateView(UpdateView):
    model = User
    context_object_name = "target_user"
    form_class = AccountUpdateForm
    success_url = reverse_lazy("SP_app:hello_world")
    template_name = "SP_app/update.html"
    

@method_decorator(has_ownership, "get")
@method_decorator(has_ownership, "post")
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = "target_user"
    success_url = reverse_lazy("SP_app:login")
    template_name = "SP_app/delete.html"

Skarea/SP_app/templates/SP_app/create.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}

    <div style= "text-align:center ;max-width: 500px; margin:4rem auto;">
        <div class"mb-4>
            <h4>Sing Up !</h4>
        </div>
        <form action="{% url 'SP_app:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>
{% endblock %}

Skarea/SP_app/templates/SP_app/delete.html
{% extends "base.html" %}

{% block content %}

    <div style= "text-align:center ;max-width: 500px; margin:4rem auto;">
        <div class"mb-4>
            <h4>Are you sure?</h4>
        </div>
        <form action="{% url 'SP_app:delete' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            
            <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
        </form>
    </div>
{% endblock %}

Skarea/SP_app/templates/SP_app/detail.html
{% extends "base.html"%}

{% block content %}
<div>
<div style="text-align:center; max-width: 500px; margin:4rem auto">

    
    {% if target_user.profile %}
    <img src="{{ target_user.profile.image.url}}" alt="" style="height: 8rem; width :8rem; border-radius: 10rem" >

    <h2>
        {{target_user.profile.nickname}}
        {% if target_user == user %}
        <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
            edit
        </a>
        {% endif %}
    </h2>
    <h6 style=margin-bottom:3rem;>
        {{target_user.profile.message}}
    </h6>
    {% else %}
    {% if target_user == user %}
    <a href="{% url 'profileapp:create' %}">
        <h2>
            Create Profile
        </h2>
    </a>
    {% else %}
     <h2>닉네임 미설정</h2>
    {% endif %}
    {% endif %}

    {% if target_user == user %}
    <a href="{% url 'SP_app:update' pk=user.pk %}">
        <p>
            Change Info
        </p>
    </a>

    <a href="{% url 'SP_app:delete' pk=user.pk %}">
        <p>
            Delete yout account
        </p>
    </a>
    {% endif %}
</div>
{% endblock %} 
</div>

Skarea/SP_app/templates/SP_app/hello_world.html
{% extends "base.html" %}

{% block content %}


    <div style="border-radius:1rem; margin: 2rem; text-align: center">
            <h1 style="font-family: 'lobster' , cursive;">
                Hello World LIST!
            </h1> 

        <form action="/SP_app/hello_world/" method="post">
            {% csrf_token %}
            <div>
                <input type="text" name="hello_world_input">
            </div>
            <div>
                <input type="submit" class="btn btn-primary" value="POST">
            </div>

        </form>

        {% if hello_world_list %}
            {% for hello_world in hello_world_list %}
            <h4>
                {{ hello_world.text }}
            </h4>

            {% endfor %}
        {% endif %}


    </div>
{% endblock %}

Skarea/SP_app/templates/SP_app/login.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block  content %}

<div style="text-align: center; max-width: 500px; margin:4rem auto;">
    <div>
        <h4>Login</h4>
    </div>
    <div>
        <form action="" method="post">
            {% csrf_token %}

            <!--{{ form }}-->
            

            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>
</div>
{% endblock %}

Skarea/SP_app/templates/SP_app/update.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}

    <div style= "text-align:center ;max-width: 500px; margin:4rem auto;">
        <div class"mb-4>
            <h4>Change Info !</h4>
        </div>
        <form action="{% url 'SP_app:update' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>
{% endblock %}